### PR TITLE
v0.9.5

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
Can I ask which other package, and why they're unable to use a newer version?

**Comment by thewchan** [comment]
https://github.com/conda-forge/kats-feedstock/pull/4

**Comment by WardBrian** [comment]
It seems like it might be a transient dependency through Prophet, which I've actually been recently working on getting a new version out of. I am pretty sure that there would be absolutely no issue using 0.9.7. Using 1.0.0 would only be an issue if they used deprecated features but I know prophet itself did not.

**Comment by thewchan** [comment]
Perhaps... I'm not sure myself; but we recent were contacted by the team at Facebook saying that the conda forge version of the package doesn't work, so I'm reworking it right now and the first step is just trying to get all the dependency to match up to ensure everyone is on the same page right now.

**Comment by WardBrian** [comment]
https://github.com/conda-forge/prophet-feedstock/pull/21 may be of interest to this. If the issue is via prophet internally, my guess is the fix will be related to the linked issues there

**Comment by thewchan** [comment]
Maybe? I'm actually not entirely sure what the FB team meant when they said it's not working on their end, they didn't quite elaborate.

**Comment by WardBrian** [comment]
Some pretty serious issues in cmdstanpy have been found and fixed since 0.9.5. If there's no other option I can make a branch for this to be merged to but I think it's worth checking if the software would work with a newer version of cmdstanpy - prophet, for example, was able to update with no code changes

**Comment by thewchan** [comment]
I can reach out to the FB team on the feedstock, mind if I tag you there?

**Comment by WardBrian** [comment]
Not at all, happy to help if I can

**Comment by thewchan** [comment]
Waiting to hear back from FB; but this might be ready to go otherwise

**Comment by WardBrian** [comment]
Progress on the package which wanted this seems to have stalled. I'm not sure anyone should really be using a pre-1.0 by now, so I am going to close this at the moment.

**Pull request closed without merging**
