### PR TITLE
Depend on cmdstan

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
That seems suspicious... the SHA256 changed???

**Comment by WardBrian** [comment]
Yes, disconcertingly it has

**Comment by maresb** [comment]
That really should not happen. I think this is worth looking into...

**Comment by WardBrian** [comment]
Downloaded myself to confirm and yes:

```
sha256sum cmdstanpy-0.9.76.tar.gz 
c6b8e6236d923ccdc54f19eb9c19a70a17f0ed5c1aa3bd9e81a264e0390dfcd6  cmdstanpy-0.9.76.tar.gz
```

**Comment by WardBrian** [comment]
The SHA hash on pypi for this version is also different `56cc2f444bd871ef3239d75c5ffd97a2e71ab125dd3327e8618bb9fef0acc89f`. What in the world?

**Comment by WardBrian** [comment]
@mitzimorris - any idea why the SHA256 hash of Github's `cmdstanpy-0.9.76.tar.gz` would have changed since June 10?

**Comment by mitzimorris** [comment]
> @mitzimorris - any idea why the SHA256 hash of Github's `cmdstanpy-0.9.76.tar.gz` would have changed since June 10?

I don't know - let's ask @serban-nicusor-toptal - Nick, what's up with SHA hash?

**Comment by serban-nicusor-toptal** [comment]
Hey, I think that happened because at that moment there was a bug in the ci ( building docs wasn't working ) and we had to re-run the pipeline after this [fix](https://github.com/stan-dev/cmdstanpy/commit/1e1c8a2061388b5672e9e8faae17334b3e369cb5) see [release/v0.9.76](https://github.com/stan-dev/cmdstanpy/tree/release/v0.9.76).

**Comment by ahartikainen** [comment]
pypi only has the source (no external data).

**Comment by WardBrian** [comment]
The update to this package was opened by a bot automatically, presumably at the first tagging, hence this issue. It sounds safe to update the hash and proceed, thank you all for the clarification!

**Review by WardBrian — APPROVED** [review]

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
